name: generate animation

on:
  schedule: # execute every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch: # allow manual trigger

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: antonioduarte07
          svg_out_path: github-contribution-grid-snake.svg

      - name: Push to output branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b output 2>/dev/null || git checkout output
          git add github-contribution-grid-snake.svg
          git diff --staged --quiet || git commit -m "Update github-contribution-grid-snake.svg"
          git push origin output --force
